name: Upload Go test results

on: [push, pull_request]

jobs:
  ci:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20.x' ]
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Node deps
        run: npm i -g husky typescript
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get .
      - name: Test with Go & Output
        run: go test ./cmd -json > TestResults-${{ matrix.go-version }}.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v3
        with:
          name: Go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json